### ISSUE TITLE
Make change to README.md to fix homebrew installation method

### ISSUE THREAD

**Issue by krosseyed** [jftuga/DateTimeMate#3]
The README.md file says to run the following code to install on homebrew:

`brew tap jftuga/homebrew-tap; brew update; brew install jftuga/tap/DateTimeMate`

However, there is no DateTimemate, just dtmate. I would suggest the following change:

`brew tap jftuga/homebrew-tap; brew update; brew install jftuga/tap/dtmate`

If you want to share this repo with me, I can make the edit. This app works great by the way!

**Comment by jftuga** [comment]
Fixed here:

https://github.com/jftuga/DateTimeMate/pull/4/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R41
